source "https://rubygems.org"

# GitHub Pages gem for compatibility
gem "github-pages", group: :jekyll_plugins

# GitHub Pages compatible plugins
group :jekyll_plugins do
  gem "jekyll-relative-links"
  gem "jekyll-optional-front-matter"
  gem "jekyll-readme-index"
end